# Generated by Django 4.0.4 on 2022-06-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Problem',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='reason',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='questions',
            new_name='question',
        ),
    ]
